server:
  port: ${SERVER_PORT}

eureka:
  instance:
    appname: licensing-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:8761/eureka/ # localhost 기동시
      defaultZone: http://host.docker.internal:8761/eureka/ # docker 기동시
